<?php
declare(strict_types=1);

/**
 * Authenticated symmetric encryption (AES-256-GCM) for secrets the panel
 * has to hold on to for a while - currently the source-server credentials
 * of an in-progress cPanel migration, which the background runner needs
 * after the request that collected them has finished.
 *
 * Key: Config::APP_KEY (generated by install.sh). Installs that predate
 * APP_KEY derive a key from the app DB password instead, so upgrading
 * doesn't require re-running the installer first - both live in the same
 * root/frankenphp-readable Config.php, so neither is weaker than the other.
 */
final class Crypto
{
    private const CIPHER = 'aes-256-gcm';

    private static function key(): string
    {
        $material = (defined('Config::APP_KEY') && !str_starts_with((string) constant('Config::APP_KEY'), '__'))
            ? (string) constant('Config::APP_KEY')
            : Config::DB_PASS;
        return hash_hkdf('sha256', $material, 32, 'jinnpanel-secrets-v1');
    }

    public static function encrypt(string $plain): string
    {
        $iv = random_bytes(12);
        $tag = '';
        $ct = openssl_encrypt($plain, self::CIPHER, self::key(), OPENSSL_RAW_DATA, $iv, $tag);
        if ($ct === false) {
            throw new RuntimeException('Encryption failed.');
        }
        return 'v1:' . base64_encode($iv . $tag . $ct);
    }

    public static function decrypt(string $blob): string
    {
        if (!str_starts_with($blob, 'v1:')) {
            throw new RuntimeException('Unknown secret format.');
        }
        $raw = base64_decode(substr($blob, 3), true);
        if ($raw === false || strlen($raw) < 29) {
            throw new RuntimeException('Corrupt secret.');
        }
        $plain = openssl_decrypt(substr($raw, 28), self::CIPHER, self::key(), OPENSSL_RAW_DATA, substr($raw, 0, 12), substr($raw, 12, 16));
        if ($plain === false) {
            throw new RuntimeException('Secret could not be decrypted (APP_KEY changed?).');
        }
        return $plain;
    }

    public static function randomPassword(int $length = 20): string
    {
        $alphabet = 'abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789';
        $out = '';
        for ($i = 0; $i < $length; $i++) {
            $out .= $alphabet[random_int(0, strlen($alphabet) - 1)];
        }
        return $out;
    }
}
